import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex w-screen min-h-screen flex-col items-center justify-center mt-5 md:mt-0 relative bg-[#0f273d] pb-20'>{children}</body>
    </html>
  )
}
